name: Stockfish
on:
  #workflow_call:
  push:
    branches:
      - Test_Actions2
jobs:
  Stockfish:
    name: ${{ matrix.config.name }} ${{ matrix.binaries }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }}
      EXT: ${{ matrix.config.ext }}
      OS: ${{ matrix.config.os }}
      BINARY: ${{ matrix.binaries }}
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu 20.04 GCC",
              os: ubuntu-20.04,
              compiler: g++,
              comp: gcc,
              shell: 'bash {0}'
            }
          - {
              name: "MacOS 12 Apple Clang",
              os: macos-12,
              compiler: clang++,
              comp: clang,
              shell: 'bash {0}'
            }
          - {
              name: "Windows 2022 Mingw-w64 GCC x86_64",
              os: windows-2022,
              compiler: g++,
              comp: mingw,
              msys_sys: 'mingw64',
              msys_env: 'x86_64-gcc',
              shell: 'msys2 {0}',
              ext: .exe
            }
        binaries:
          - x86-64
          - x86-64-modern
          - x86-64-avx2
        exclude:
          - binaries: x86-64-avx2
            config: {os: macos-12}

          - {
              name: "Ubuntu 20.04 NDK armv8",
              os: ubuntu-20.04,
              compiler: aarch64-linux-android23-clang++,
              comp: ndk,
              run_armv8_tests: false,
              shell: 'bash {0}'
            }
          - {
              name: "Ubuntu 20.04 NDK armv7",
              os: ubuntu-20.04,
              compiler: armv7a-linux-androideabi21-clang++,
              comp: ndk,
              run_armv7_tests: false,
              shell: 'bash {0}'
            }



    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download required linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update

      - name: Setup msys and install required packages
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.config.msys_sys}}
          install: mingw-w64-${{matrix.config.msys_env}} make git expect

      - name: Download the used network from the fishtest framework
        run: |
          make net

      - name: Check compiler
        run: |
          export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          $COMPILER -v

      - name: Test help target
        run: |
          make help

      # Compile profile guided builds

      - name: Compile ${{ matrix.binaries }} build
        run: |
          make clean
          make -j2 profile-build ARCH=$BINARY COMP=$COMP
          strip ./stockfish$EXT
          mv ./stockfish$EXT ../stockfish-$OS-$BINARY$EXT

      - name: Remove non src files
        run: rm -f *.o .depend *.nnue

      - name: Create tar archive.
        run: |
          cd ..
          mkdir stockfish
          cp -r src stockfish/
          cp stockfish-$OS-$BINARY$EXT stockfish/
          cp "Top CPU Contributors.txt" stockfish/
          cp Copying.txt stockfish/
          cp AUTHORS stockfish/
          tar -cvf stockfish-$OS-$BINARY.tar stockfish

      # Compile armv8 

      - name: Test armv8 build
        if: ${{ matrix.config.run_armv8_tests }}
        run: |
          function get_full_ndk_version {
            majorVersion=$1
            ndkFullVersion=$($SDKMANAGER --list | grep "ndk;${majorVersion}.*" | awk '{gsub("ndk;", ""); print $1}' | sort -V | tail -n1)
            echo "$ndkFullVersion"
          }
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
          ndkDefaultFullVersion=$(get_full_ndk_version "23")
          ln -sf $ANDROID_SDK_ROOT/ndk/$ndkDefaultFullVersion $ANDROID_NDK_ROOT
          export PATH=$ANDROID_NDK_HOME:$PATH
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export LDFLAGS="-static -Wno-unused-command-line-argument"

          cd ../jni
          cp Application_v8.mk Application.mk
          ndk-build
          cd ../libs/arm64-v8a
          cp Stockfish ../../src/stockfishv8
          cd ../../src/
      - uses: actions/upload-artifact@v3
        with:
          path: /home/runner/work/StockfishNPS/StockfishNPS/src/stockfishv8
          
      # Compile armv7 

      - name: Test armv7 build
        if: ${{ matrix.config.run_armv7_tests }}
        run: |
          function get_full_ndk_version {
            majorVersion=$1
            ndkFullVersion=$($SDKMANAGER --list | grep "ndk;${majorVersion}.*" | awk '{gsub("ndk;", ""); print $1}' | sort -V | tail -n1)
            echo "$ndkFullVersion"
          }
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
          ndkDefaultFullVersion=$(get_full_ndk_version "23")
          ln -sf $ANDROID_SDK_ROOT/ndk/$ndkDefaultFullVersion $ANDROID_NDK_ROOT
          export PATH=$ANDROID_NDK_HOME:$PATH
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export LDFLAGS="-static -Wno-unused-command-line-argument"
    
          cd ../jni
          cp Application_v7.mk Application.mk
          ndk-build
          cd ../libs/armeabi-v7a
          cp Stockfish ../../src/stockfishv7
          cd ../../src/
      - uses: actions/upload-artifact@v3
        with:
          path: /home/runner/work/StockfishNPS/StockfishNPS/src/stockfishv7



      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: stockfish-${{ matrix.config.os }}-${{ matrix.binaries }}
          path: |
            stockfish-${{ matrix.config.os }}-${{ matrix.binaries }}.tar
