name: SFnpsArmTest
on:
  workflow_dispatch:
jobs:
  SFnpsArmTest:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }}
      CXXFLAGS: 
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu 22.04 NDK armv8",
              os: ubuntu-22.04,
              compiler: aarch64-linux-android21-clang++,
              comp: ndk,
              run_armv8_tests: true,
              shell: 'bash {0}'
            }

    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download qemu-user packages
        run: |
          sudo apt update
          sudo apt install qemu-user

      - name: Download the used network from the fishtest framework
        run: make net

      - name: Check compiler
        run: |
          export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          $COMPILER -v

      # armv8 tests

      - name: Test armv8 build
        run: |
            export PATH=$ANDROID_NDK_HOME:$PATH
            export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
            #export LDFLAGS="-static -Wno-unused-command-line-argument"

            #make net
            cp nn-*.nnue ../jni
            cd ../jni
            cp Application_v8.mk Application.mk
            ndk-build
            cd ../libs/arm64-v8a
            cp Stockfish ../../src/SFnps_armv8
            #Net is in /src and /jni for tests
            cd ../../src/
            #./SFnps_armv8 bench >> BenchOutput8.txt

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.config.run_armv8_tests }}
        with:
          name: SFnps-armv8
          path: /home/runner/work/StockfishNPS/StockfishNPS/src/SFnps_armv8
